### ISSUE TITLE
Swiping events in app

### ISSUE THREAD

**Issue by bcb** [tricycle/elm-infinite-gallery#3]
In my app, I need to act when a swipe event occurs.

**Comment by everlaat** [comment]
@bcb Would exposing the `Gallery.Msg` type sufficient for your use case?
You can then handle any event you would like to act by case matching on the msg in your own update function.

**Comment by bcb** [comment]
Yes that sounds perfect.

**Comment by bcb** [comment]
It seems `Msg` is already exposed, but it needs to be `Msg(..)` to expose the message types like "Next".

I'll send through a PR for this.
